
package gpw.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.6
 * Sun Jul 30 01:35:40 UYT 2017
 * Generated source version: 3.1.6
 */

@XmlRootElement(name = "obtenerPersonasNoSinc", namespace = "http://localhost:8080")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "obtenerPersonasNoSinc", namespace = "http://localhost:8080")

public class ObtenerPersonasNoSinc {

    @XmlElement(name = "paramObtPersonasNoSinc")
    private gpw.ws.datatypes.persona.ParamObtPersonasNoSinc paramObtPersonasNoSinc;

    public gpw.ws.datatypes.persona.ParamObtPersonasNoSinc getParamObtPersonasNoSinc() {
        return this.paramObtPersonasNoSinc;
    }

    public void setParamObtPersonasNoSinc(gpw.ws.datatypes.persona.ParamObtPersonasNoSinc newParamObtPersonasNoSinc)  {
        this.paramObtPersonasNoSinc = newParamObtPersonasNoSinc;
    }

}

