
package gpw.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.6
 * Sun Sep 03 19:49:57 UYT 2017
 * Generated source version: 3.1.6
 */

@XmlRootElement(name = "obtenerPedidosNoSincResponse", namespace = "http://localhost:8080")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "obtenerPedidosNoSincResponse", namespace = "http://localhost:8080")

public class ObtenerPedidosNoSincResponse {

    @XmlElement(name = "resultObtPedidosNoSinc")
    private gpw.ws.datatypes.pedido.ResultObtPedidosNoSinc resultObtPedidosNoSinc;

    public gpw.ws.datatypes.pedido.ResultObtPedidosNoSinc getResultObtPedidosNoSinc() {
        return this.resultObtPedidosNoSinc;
    }

    public void setResultObtPedidosNoSinc(gpw.ws.datatypes.pedido.ResultObtPedidosNoSinc newResultObtPedidosNoSinc)  {
        this.resultObtPedidosNoSinc = newResultObtPedidosNoSinc;
    }

}

