
package gpw.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.6
 * Sat Jul 22 22:10:25 UYT 2017
 * Generated source version: 3.1.6
 */

@XmlRootElement(name = "obtPersonasNoSincResponse", namespace = "http://localhost:8080")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "obtPersonasNoSincResponse", namespace = "http://localhost:8080")

public class ObtPersonasNoSincResponse {

    @XmlElement(name = "resultObtPersonasNoSinc")
    private gpw.ws.datatypes.persona.ResultObtPersonasNoSinc resultObtPersonasNoSinc;

    public gpw.ws.datatypes.persona.ResultObtPersonasNoSinc getResultObtPersonasNoSinc() {
        return this.resultObtPersonasNoSinc;
    }

    public void setResultObtPersonasNoSinc(gpw.ws.datatypes.persona.ResultObtPersonasNoSinc newResultObtPersonasNoSinc)  {
        this.resultObtPersonasNoSinc = newResultObtPersonasNoSinc;
    }

}

