
package gpw.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.6
 * Sat Jul 22 22:10:25 UYT 2017
 * Generated source version: 3.1.6
 */

@XmlRootElement(name = "recibirPersonasSinc", namespace = "http://localhost:8080")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recibirPersonasSinc", namespace = "http://localhost:8080")

public class RecibirPersonasSinc {

    @XmlElement(name = "paramRecPersonasSinc")
    private gpw.ws.datatypes.persona.ParamRecPersonasSinc paramRecPersonasSinc;

    public gpw.ws.datatypes.persona.ParamRecPersonasSinc getParamRecPersonasSinc() {
        return this.paramRecPersonasSinc;
    }

    public void setParamRecPersonasSinc(gpw.ws.datatypes.persona.ParamRecPersonasSinc newParamRecPersonasSinc)  {
        this.paramRecPersonasSinc = newParamRecPersonasSinc;
    }

}

