
package gpw.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.6
 * Sat Sep 09 22:42:42 UYT 2017
 * Generated source version: 3.1.6
 */

@XmlRootElement(name = "recibirPersonasASinc", namespace = "http://192.168.1.2:8080")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recibirPersonasASinc", namespace = "http://192.168.1.2:8080")

public class RecibirPersonasASinc {

    @XmlElement(name = "paramRecPersonasASinc")
    private gpw.ws.datatypes.persona.ParamRecPersonasASinc paramRecPersonasASinc;

    public gpw.ws.datatypes.persona.ParamRecPersonasASinc getParamRecPersonasASinc() {
        return this.paramRecPersonasASinc;
    }

    public void setParamRecPersonasASinc(gpw.ws.datatypes.persona.ParamRecPersonasASinc newParamRecPersonasASinc)  {
        this.paramRecPersonasASinc = newParamRecPersonasASinc;
    }

}

