
package gpw.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.6
 * Sat Jul 22 22:10:25 UYT 2017
 * Generated source version: 3.1.6
 */

@XmlRootElement(name = "recibirPersonasSincResponse", namespace = "http://localhost:8080")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recibirPersonasSincResponse", namespace = "http://localhost:8080")

public class RecibirPersonasSincResponse {

    @XmlElement(name = "resultRecPersonasSinc")
    private gpw.ws.datatypes.persona.ResultRecPersonasSinc resultRecPersonasSinc;

    public gpw.ws.datatypes.persona.ResultRecPersonasSinc getResultRecPersonasSinc() {
        return this.resultRecPersonasSinc;
    }

    public void setResultRecPersonasSinc(gpw.ws.datatypes.persona.ResultRecPersonasSinc newResultRecPersonasSinc)  {
        this.resultRecPersonasSinc = newResultRecPersonasSinc;
    }

}

