
package gpw.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.6
 * Mon Sep 25 03:09:09 UYT 2017
 * Generated source version: 3.1.6
 */

@XmlRootElement(name = "recibirPedidosASinc", namespace = "http://localhost:8080")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recibirPedidosASinc", namespace = "http://localhost:8080")

public class RecibirPedidosASinc {

    @XmlElement(name = "paramRecPedidosASinc")
    private gpw.ws.datatypes.pedido.ParamRecPedidosASinc paramRecPedidosASinc;

    public gpw.ws.datatypes.pedido.ParamRecPedidosASinc getParamRecPedidosASinc() {
        return this.paramRecPedidosASinc;
    }

    public void setParamRecPedidosASinc(gpw.ws.datatypes.pedido.ParamRecPedidosASinc newParamRecPedidosASinc)  {
        this.paramRecPedidosASinc = newParamRecPedidosASinc;
    }

}

