
package gpw.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.6
 * Fri Aug 04 22:35:57 UYT 2017
 * Generated source version: 3.1.6
 */

@XmlRootElement(name = "recibirPersonasASincResponse", namespace = "http://localhost:8080")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recibirPersonasASincResponse", namespace = "http://localhost:8080")

public class RecibirPersonasASincResponse {

    @XmlElement(name = "resultRecPersonasASinc")
    private gpw.ws.datatypes.persona.ResultRecPersonasASinc resultRecPersonasASinc;

    public gpw.ws.datatypes.persona.ResultRecPersonasASinc getResultRecPersonasASinc() {
        return this.resultRecPersonasASinc;
    }

    public void setResultRecPersonasASinc(gpw.ws.datatypes.persona.ResultRecPersonasASinc newResultRecPersonasASinc)  {
        this.resultRecPersonasASinc = newResultRecPersonasASinc;
    }

}

