
package gpw.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.6
 * Sat Sep 09 22:42:42 UYT 2017
 * Generated source version: 3.1.6
 */

@XmlRootElement(name = "recibirProductosASinc", namespace = "http://192.168.1.2:8080")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recibirProductosASinc", namespace = "http://192.168.1.2:8080")

public class RecibirProductosASinc {

    @XmlElement(name = "paramRecProductosASinc")
    private gpw.ws.datatypes.producto.ParamRecProductosASinc paramRecProductosASinc;

    public gpw.ws.datatypes.producto.ParamRecProductosASinc getParamRecProductosASinc() {
        return this.paramRecProductosASinc;
    }

    public void setParamRecProductosASinc(gpw.ws.datatypes.producto.ParamRecProductosASinc newParamRecProductosASinc)  {
        this.paramRecProductosASinc = newParamRecProductosASinc;
    }

}

