
package gpw.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.6
 * Sat Sep 09 22:42:42 UYT 2017
 * Generated source version: 3.1.6
 */

@XmlRootElement(name = "recibirProductosASincResponse", namespace = "http://192.168.1.2:8080")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recibirProductosASincResponse", namespace = "http://192.168.1.2:8080")

public class RecibirProductosASincResponse {

    @XmlElement(name = "resultRecProductosASinc")
    private gpw.ws.datatypes.producto.ResultRecProductosASinc resultRecProductosASinc;

    public gpw.ws.datatypes.producto.ResultRecProductosASinc getResultRecProductosASinc() {
        return this.resultRecProductosASinc;
    }

    public void setResultRecProductosASinc(gpw.ws.datatypes.producto.ResultRecProductosASinc newResultRecProductosASinc)  {
        this.resultRecProductosASinc = newResultRecProductosASinc;
    }

}

