
package gpw.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.6
 * Sat Sep 09 22:42:42 UYT 2017
 * Generated source version: 3.1.6
 */

@XmlRootElement(name = "servFuncionalResponse", namespace = "http://192.168.1.2:8080")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "servFuncionalResponse", namespace = "http://192.168.1.2:8080")

public class ServFuncionalResponse {

    @XmlElement(name = "resultServFuncional")
    private gpw.ws.datatypes.wsfunc.ResultServFuncional resultServFuncional;

    public gpw.ws.datatypes.wsfunc.ResultServFuncional getResultServFuncional() {
        return this.resultServFuncional;
    }

    public void setResultServFuncional(gpw.ws.datatypes.wsfunc.ResultServFuncional newResultServFuncional)  {
        this.resultServFuncional = newResultServFuncional;
    }

}

