
package gpw.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.6
 * Mon Sep 25 03:09:09 UYT 2017
 * Generated source version: 3.1.6
 */

@XmlRootElement(name = "servFuncional", namespace = "http://localhost:8080")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "servFuncional", namespace = "http://localhost:8080")

public class ServFuncional {


}

