
package gpw.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.6
 * Sun Jul 30 01:35:40 UYT 2017
 * Generated source version: 3.1.6
 */

@XmlRootElement(name = "servicioFuncional", namespace = "http://localhost:8080")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "servicioFuncional", namespace = "http://localhost:8080")

public class ServicioFuncional {


}

